apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-neo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt-neo
  template:
    metadata:
      labels:
        app: gpt-neo
    spec:
      containers:
      - name: gpt-neo
        image: gpt-neo:amd64
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: gpt-neo
spec:
  selector:
    app: gpt-neo
  ports:
  - port: 8000
    targetPort: 8000