apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama
  template:
    metadata:
      labels:
        app: llama
    spec:
      containers:
      - name: llama
        image: llama:amd64
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: llama
spec:
  selector:
    app: llama
  ports:
  - port: 8000
    targetPort: 8000