apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-llama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distributed-llama
  template:
    metadata:
      labels:
        app: distributed-llama
    spec:
      containers:
      - name: distributed-llama
        image: myicap/distllamaroot:arm64  # Replace with your built image
        ports:
        - containerPort: 9990
        command: ["./dllama-api", "--model", "models/llama3_1_8b_instruct_q40/dllama_model_llama3_1_8b_instruct_q40.m", "--tokenizer", "models/llama3_1_8b_instruct_q40/dllama_tokenizer_llama3_1_8b_instruct_q40.t", "--buffer-float-type", "q80", "--prompt", "'Hello?'", "--steps", "256", "--nthreads", "4", "--workers", "172.18.0.2:9998"]
---
apiVersion: v1
kind: Service
metadata:
  name: distributed-llama-service
spec:
  type: NodePort
  ports:
  - port: 9990
    targetPort: 9990
    nodePort: 30000  # Optional: specify a node port
  selector:
    app: distributed-llama